project:
  type: website
  output-dir: docs

website:
  title: "yuhakim.github.io"
  navbar:
    left:
      - href: index.qmd
        text: Home
      - about.qmd
      - write-up.qmd
      - visualizations.qmd

format:
  html:
    theme: litera
    css: styles.css
    toc: true

editor: visual

